berichtsheft_base_dashboard:
    pattern:  /
    defaults: { _controller: BerichtsheftBaseBundle:Berichtsheft:dashboard }

berichtsheft_base_timetable:
    pattern:  /timetable
    defaults: { _controller: BerichtsheftBaseBundle:Berichtsheft:timetable }

berichtsheft_base_show:
    pattern:  /show
    defaults: { _controller: BerichtsheftBaseBundle:Berichtsheft:show }

berichtsheft_base_pdf:
    pattern:  /show/pdf
    defaults: { _controller: BerichtsheftBaseBundle:Berichtsheft:pdf }

berichtsheft_base_tbs:
    pattern:  /show/tbs
    defaults: { _controller: BerichtsheftBaseBundle:Berichtsheft:tbs }

berichtsheft_base_generate:
    pattern:  /generate
    defaults: { _controller: BerichtsheftBaseBundle:Berichtsheft:generate }

berichtsheft_base_benutzerhandbuch:
    pattern:  /benutzerhandbuch
    defaults: { _controller: BerichtsheftBaseBundle:Content:benutzerhandbuch }