parameters:
#    berichtsheft_base.example.class: Berichtsheft\BaseBundle\Example

services:
#    berichtsheft_base.example:
#        class: %berichtsheft_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
