parameters:
    berichtsheft_base.worklog_retriever.jira.class: Berichtsheft\BaseBundle\Worklog\Jira\JiraWorklogRetriever
    berichtsheft_base.berichtsheft_builder.class: Berichtsheft\BaseBundle\BerichtsheftBuilder\BerichtsheftBuilder

services:
    berichtsheft_base.worklog_retriever.jira:
        class: %berichtsheft_base.worklog_retriever.jira.class%
        arguments: [@jira_api.issue, @jira_api.project, @jira_api.search]
    berichtsheft_base.berichtsheft_builder:
        class: %berichtsheft_base.berichtsheft_builder.class%
        arguments: [@berichtsheft_base.worklog_retriever.jira]