parameters:
    berichtsheft_base.worklog_retriever.jira.class: Berichtsheft\BaseBundle\Worklog\Jira\JiraWorklogRetriever

services:
    berichtsheft_base.worklog_retriever.jira:
        class: %berichtsheft_base.worklog_retriever.jira.class%
        arguments: [@jira_api.issue, @jira_api.project, @jira_api.search]
